#!/usr/bin/env bash
# Install hamLLM from this checkout: a `hamllm` launcher, MCP registration for Claude Code
# and Codex, and (opt-in) model profiling and offload instructions. No pip, no sudo.
#
#   scripts/install.sh                       launcher + register MCP in whichever of claude/codex exist
#   scripts/install.sh --profile-all         ...and profile every installed text model (slow)
#   scripts/install.sh --instructions        ...and add an offload rule to ~/.claude/CLAUDE.md and ~/.codex/AGENTS.md
#   scripts/install.sh --dry-run             show what would happen, change nothing
#   scripts/install.sh --uninstall           remove the launcher, registrations and instruction blocks
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
MCP_MODEL="${HAMLLM_MCP_MODEL:-code}"   # alias the MCP server uses as its default model
REPEATS=5
DRY=0 UNINSTALL=0 DO_MCP=1 DO_INSTRUCTIONS=0 PROFILE_ALL=0
PROFILE_MODELS=()
ONLY=""

usage() { sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; cat <<'EOF'

Options:
  --prefix DIR        install the launcher to DIR/bin (default ~/.local; env PREFIX)
  --claude | --codex  register only with that client (default: every one found on PATH)
  --no-mcp            skip MCP registration
  --profile TAG       run `hamllm eval --save` for TAG (repeatable)
  --profile-all       run `hamllm eval --save --all`
  --repeats N         repeats per eval case (default 5)
  --instructions      add the offload rule block to the clients' global instruction files
  --dry-run, --uninstall, -h
Env: HAMLLM_MCP_MODEL (default "code"), HAMLLM_HOST (passed to the MCP server if set)
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift ;;
    --claude|--codex) ONLY="${1#--}" ;;
    --no-mcp) DO_MCP=0 ;;
    --profile) PROFILE_MODELS+=("$2"); shift ;;
    --profile-all) PROFILE_ALL=1 ;;
    --repeats) REPEATS="$2"; shift ;;
    --instructions) DO_INSTRUCTIONS=1 ;;
    --dry-run) DRY=1 ;;
    --uninstall) UNINSTALL=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

BIN="$PREFIX/bin/hamllm"
BEGIN_MARK="<!-- hamllm:begin -->"
END_MARK="<!-- hamllm:end -->"
INSTRUCTION_FILES=("$HOME/.claude/CLAUDE.md" "$HOME/.codex/AGENTS.md")

say() { printf '%s\n' "$*"; }
run() { printf '+ %s\n' "$*"; [ "$DRY" = 1 ] || "$@"; }
have() { command -v "$1" >/dev/null 2>&1; }
wants() { [ -z "$ONLY" ] || [ "$ONLY" = "$1" ]; }

PY="$(command -v python3 || true)"
[ -n "$PY" ] || { echo "python3 not found on PATH" >&2; exit 1; }
"$PY" -c 'import sys; sys.exit(sys.version_info < (3, 11))' \
  || { echo "hamLLM needs Python 3.11 or newer (found $("$PY" -V 2>&1))" >&2; exit 1; }

# Add (mode=add) or remove (mode=remove) the marked offload block in a markdown file, idempotently.
edit_block() {
  "$PY" -I - "$1" "$2" "$BEGIN_MARK" "$END_MARK" <<'PYEOF'
import pathlib, re, sys
path, mode, begin, end = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3], sys.argv[4]
block = f"""{begin}
## Local model offload (hamLLM)
For cheap, low-stakes work (summaries, commit messages, classification, log triage, JSON extraction),
call the `ask_local` tool from the `hamllm` MCP server first. Do not use it for hard reasoning, and
verify what it returns before relying on it. Offloading is not private: the prompt still comes from you.
{end}
"""
text = path.read_text() if path.exists() else ""
text = re.sub(re.escape(begin) + r".*?" + re.escape(end) + r"\n?", "", text, flags=re.S).rstrip("\n")
if mode == "add":
    text = (text + "\n\n" if text else "") + block
elif not text:
    if path.exists():
        path.unlink()
    sys.exit(0)
else:
    text += "\n"
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(text)
PYEOF
}

mcp_env_args() {
  printf '%s\0' --env "HAMLLM_MODEL=$MCP_MODEL"
  [ -z "${HAMLLM_HOST:-}" ] || printf '%s\0' --env "HAMLLM_HOST=$HAMLLM_HOST"
}

if [ "$UNINSTALL" = 1 ]; then
  have claude && wants claude && { run claude mcp remove --scope user hamllm || true; }
  have codex && wants codex && { run codex mcp remove hamllm || true; }
  for f in "${INSTRUCTION_FILES[@]}"; do
    [ -f "$f" ] && grep -qF "$BEGIN_MARK" "$f" && { say "+ remove hamllm block from $f"; [ "$DRY" = 1 ] || edit_block "$f" remove; }
  done
  run rm -f "$BIN"
  say "Uninstalled. Profiles remain in \${HAMLLM_STATE_DIR:-~/.local/state/hamllm} (delete by hand if unwanted)."
  exit 0
fi

# 1. launcher: runs this checkout, so `git pull` is the whole upgrade story
say "== launcher: $BIN (runs $REPO/src)"
if [ "$DRY" = 1 ]; then
  say "+ write $BIN"
else
  mkdir -p "$PREFIX/bin"
  printf '#!/bin/sh\n# Generated by hamLLM scripts/install.sh; runs the checkout at %s\nPYTHONPATH="%s/src${PYTHONPATH:+:$PYTHONPATH}" exec "%s" -m hamllm "$@"\n' \
    "$REPO" "$REPO" "$PY" > "$BIN"
  chmod +x "$BIN"
  "$BIN" --version
fi
case ":$PATH:" in *":$PREFIX/bin:"*) ;; *) say "NOTE: $PREFIX/bin is not on your PATH; add it to use \`hamllm\` directly." ;; esac

# 2. is Ollama reachable? (warn only: you can install before starting it)
if [ "$DRY" = 0 ]; then
  "$BIN" doctor || say "WARN: Ollama not healthy for the default model yet; install continues."
fi

# 3. profile models (opt-in: minutes per model)
for model in "${PROFILE_MODELS[@]+"${PROFILE_MODELS[@]}"}"; do
  say "== profiling $model ($REPEATS repeats)"
  run "$BIN" eval --save --repeats "$REPEATS" --model "$model" || say "WARN: $model did not pass its eval (profile still saved)"
done
if [ "$PROFILE_ALL" = 1 ]; then
  say "== profiling all installed text models ($REPEATS repeats; this takes a while)"
  run "$BIN" eval --save --all --repeats "$REPEATS" || say "WARN: no model passed; profiles saved anyway"
fi

# 4. register the MCP server
if [ "$DO_MCP" = 1 ]; then
  env_args=(); while IFS= read -r -d '' a; do env_args+=("$a"); done < <(mcp_env_args)
  registered=0
  if have claude && wants claude; then
    say "== Claude Code"
    [ "$DRY" = 1 ] || claude mcp remove --scope user hamllm >/dev/null 2>&1 || true
    run claude mcp add --scope user "${env_args[@]}" hamllm -- "$BIN" mcp && registered=1
  fi
  if have codex && wants codex; then
    say "== Codex"
    [ "$DRY" = 1 ] || codex mcp remove hamllm >/dev/null 2>&1 || true
    if run codex mcp add "${env_args[@]}" hamllm -- "$BIN" mcp; then registered=1; else
      say "WARN: \`codex mcp add\` failed; add this to ~/.codex/config.toml instead:"
      printf '[mcp_servers.hamllm]\ncommand = "%s"\nargs = ["mcp"]\n[mcp_servers.hamllm.env]\nHAMLLM_MODEL = "%s"\n' "$BIN" "$MCP_MODEL"
    fi
  fi
  [ "$registered" = 1 ] || say "No claude/codex CLI registered (none found, or all failed)."
  say "== Zed (not edited automatically: settings.json is JSONC). Add under \"context_servers\":"
  printf '  "hamllm": { "command": "%s", "args": ["mcp"], "env": { "HAMLLM_MODEL": "%s" } }\n' "$BIN" "$MCP_MODEL"

  if [ "$DRY" = 0 ]; then
    out="$(printf '%s\n' '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18"}}' \
                          '{"jsonrpc":"2.0","id":2,"method":"tools/list"}' | "$BIN" mcp)"
    case "$out" in *ask_local*) say "OK: MCP server answers and offers ask_local." ;; *) echo "ERROR: MCP smoke test failed: $out" >&2; exit 1 ;; esac
  fi
fi

# 5. offload rule for the clients (opt-in; edits global instruction files)
if [ "$DO_INSTRUCTIONS" = 1 ]; then
  for f in "${INSTRUCTION_FILES[@]}"; do
    say "== offload rule -> $f"
    [ "$DRY" = 1 ] || edit_block "$f" add
  done
fi

say ""
say "Done. Next: hamllm eval --save --repeats 5 --model TAG   (profile models; 'hamllm resolve code' shows the pick)"
[ "$DO_MCP" = 0 ] || say "Then restart Claude Code / Codex / Zed and ask: use ask_local to write a commit message for this diff."
